### ISSUE TITLE
The problem about lacking two files

### ISSUE THREAD

**Issue by xiaoming3526** [xh-liu/CM-Erase-REG#1]
Hello，dear author, I'm writing to ask some questions about this code.  I have prepared everything needed in Installation part.  However when I run './experiments/scripts/eval_easy.sh GPU_ID' in Evaluation part,  two errors  occured that say:  'tee: logs/test_coco+_erase_val: No such file or  directory'  and 'tee:logs/test_coco+_erase_test: No such file or  directory '.  I am sorry that I have not been able to solve this problem. I am looking forward to hearing from you. Thank you for your attention.

**Comment by xh-liu** [comment]
Hi! You can make the "logs" folder by "mkdir logs" before running the script.

**Comment by xiaoming3526** [comment]
> Hi! You can make the "logs" folder by "mkdir logs" before running the script.

thanks!  the error solved ~
