### ISSUE TITLE
Having trouble re-produncing results on RefCOCO+

### ISSUE THREAD

**Issue by ChopinSharp** [xh-liu/CM-Erase-REG#2]
Hi there. 
I've been trying to re-produce your results on all three referring expression datasets, namely RefCOCO, RefCOCO+ and RefCOCOg. The pretrained models on RefCOCO and RefCOCOg worked as expected. But I got very poor performace on RefCOCO+ with pretrained model. 
If it's not too much trouble, could you please check whether pretrained model on RefCOCO+ is corrupted or not.
Thanks in advance~

**Comment by xh-liu** [comment]
Hi,

I checked the models and found that I uploaded the wrong model for RefCOCO+. Now I have uploaded the correct one. Please re-check the results for RefCOCO+. (https://drive.google.com/open?id=1nYiDIU4nKOTz2dyOVQ7ThPkvlSeI_Nwp
)
Thank you for pointing out and please let me know if you have further questions!

**Comment by ChopinSharp** [comment]
Thanks for your help! One more problem though. It seems that the corresponding JSON files are missing in the new version. I do have the JSON files from the old version. Are they compatible?

**Comment by ruizewang** [comment]
Hi ChopinSharp @ChopinSharp , have you solve the problem of missing the corresponding JSON files?

**Comment by ChopinSharp** [comment]
@ruizewang I didn't use pretrained model. Instead, I followed the instructions and trained the model myself. It worked just fine.
