### ISSUE TITLE
Missing model infos:   output/refcocog_umd/coco+_erase.json

### ISSUE THREAD

**Issue by ruizewang** [xh-liu/CM-Erase-REG#4]
Hi xh,
The trained models you provided at this [link](https://drive.google.com/drive/folders/1nYiDIU4nKOTz2dyOVQ7ThPkvlSeI_Nwp) only contain .pth file, but the corresponding JSON files are missing. Could you please help me figure it out?
Thanks in advance.

<img width="575" alt="image" src="https://user-images.githubusercontent.com/8149167/104126751-4bb22580-5399-11eb-93b1-d0f976fa41f2.png">

**Comment by xh-liu** [comment]
Hello,

I have uploaded the json files to the Google Drive folder. You can check if it works now.

**Comment by ruizewang** [comment]
Thanks for your quick response~ I will have a try later.

**Comment by ruizewang** [comment]
Hi @xh-liu , the .json file may be not compatible with the .pth file.
When I run ` bash ./experiments/scripts/eval_easy.sh 1`  (I tried 3 settings, including refcoco+_unc, refcoco_unc, refcocog_umd) , I occur such problem:

```
Traceback (most recent call last):
  File "./tools/eval_easy.py", line 105, in <module>
    evaluate(params)
  File "./tools/eval_easy.py", line 46, in evaluate
    model = load_model(model_path, model_opt)
  File "./tools/eval_easy.py", line 29, in load_model
    model.load_state_dict(checkpoint['model'].state_dict())
  File "/remote-home/my/anaconda3/envs/rec/lib/python2.7/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for JointMatching:
        Missing key(s) in state_dict: "sub_encoder.att_fuse.1.num_batches_tracked", "sub_matching.vis_emb_fc.1.num_batches_tracked", "sub_matching.vis_emb_fc.5.num_batches_tracked", "sub_matching.lang_emb_fc.1.num_batches_tracked", "sub_matching.lang_emb_fc.5.num_batches_tracked", "loc_matching.vis_emb_fc.1.num_batches_tracked", "loc_matching.vis_emb_fc.5.num_batches_tracked", "loc_matching.lang_emb_fc.1.num_batches_tracked", "loc_matching.lang_emb_fc.5.num_batches_tracked", "rel_matching.vis_emb_fc.1.num_batches_tracked", "rel_matching.vis_emb_fc.5.num_batches_tracked", "rel_matching.lang_emb_fc.1.num_batches_tracked", "rel_matching.lang_emb_fc.5.num_batches_tracked", "process_pool5.1.num_batches_tracked", "process_pool5.4.num_batches_tracked", "process_pool5.7.num_batches_tracked". 
```

**Comment by xh-liu** [comment]
That's wired. I will check it and let you know tomorrow. @ruizewang

**Comment by ruizewang** [comment]
Hi Xihui @xh-liu,
Thanks for your kindly help. I have found the problem.
 My PyTorch version is 0.4.1 (due to 2080Ti, cuda 9.2), which is not the same as your project requirements.

The solution is as follows:
>  In eval_easy.py,  change `model.load_state_dict(checkpoint['model'].state_dict())` to `model.load_state_dict(checkpoint['model'].state_dict(), strict=False)`, then it can normally loaded. This is due to the higher version of pytorch.

Reference:  https://github.com/lichengunc/MAttNet/issues/29
