### ISSUE TITLE
The difference between CM-Att and MattNet

### ISSUE THREAD

**Issue by ruizewang** [xh-liu/CM-Erase-REG#6]
Hi Xihui, 
Thanks for your great work again. 

I have one question: what is the difference between MattNet and your CM-Att (without erasing). It seems they are the same model. Could you please help me figure it out?

Thanks in advance.

**Comment by xh-liu** [comment]
The structure of MattNet and our CM-Att (without erasing) is very similar. The two differences are: (1) we use attention for relationship module and location module, while MattNet used feature concatenation for the location module, and max pooling for the relationship module. We choose the attention module to enable the attention-guided erasing in our next step. (2) In MattNet, the language attention is derived from only the referring expression. While in our method, the language attention is derived from the multimodal information (both referring expression and image feature). See section 3.3 "Image-Aware Query Sentence Erasing" in our paper for details.

**Comment by ruizewang** [comment]
Thanks for your quick and detailed reply~ It helps me a lot. O(∩_∩)O
